version: '3'
services:
  nginx:
    image: nginx:1.24.0-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 5433:5432
    env_file:
      - ./postgres/.env

  directus:
    image: directus/directus:10.2.1
    container_name: directus
    restart: unless-stopped
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/snapshots:/directus/snapshots
      - ./directus/extensions:/directus/extensions
    env_file:
      - ./directus/.env

  react-nextjs:
    build: ./react-nextjs
    container_name: react-nextjs
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./react-nextjs:/app/react-nextjs
