version: '3'
services:
  nginx:
    extends:
      file: docker-compose.common.yml
      service: nginx
    volumes:
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-nextjs
      - directus

  directus:
    extends:
      file: docker-compose.common.yml
      service: directus
    depends_on:
      - postgres

  postgres:
    extends:
      file: docker-compose.common.yml
      service: postgres

  react-nextjs:
    extends:
      file: docker-compose.common.yml
      service: react-nextjs
    build:
      target: development
    depends_on:
      - directus

networks:
  web-gateway:
    driver: bridge
  postgres:
    driver: bridge
